### ISSUE TITLE
标题页没有居中

### ISSUE THREAD

**Issue by LingyiHongfd** [ArnoldYuan/fduthesis2022#7]
将 \maketitle 替换为

\null  % Empty line
\nointerlineskip  % No skip for prev line
\vfill
\let\snewpage \newpage
\let\newpage \relax
\maketitle
\let \newpage \snewpage
\vfill 
\break % page break

**Comment by eurekayuan** [comment]
`\begin{titlepage}
\centering
\vspace*{\fill}
% \vspace*{}
\hei\zihao{-2}
\mytitle
\vspace*{0.5em}
\vspace*{\fill}
\end{titlepage}`
this should work
